name: Fetch TODO (cron)

on:
  schedule:
    - cron: "*/5 * * * *"   # 5분마다(UTC)
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Compute URL & fetch
        run: |
          min=$(date +%M)            # 분
          num=$((10#$min + 1))       # 현재분+1
          url="https://jsonplaceholder.typicode.com/todos/${num}"
          out="/tmp/test.json"
          curl -sS "$url" -o "$out"
          cat "$out"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test.json
          path: /tmp/test.json
